### PR TITLE
updated util.error to unsafeLog

### PR DESCRIPTION
**Pull request by tsonge**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

before changing to unsafeLog: (note how `&quot;` is being displayed in the bolded error log)
before

after:
after

**Which issue (if any) does this pull request address?**
None.
**Is there anything you'd like reviewers to focus on?**
Nope.

### CODE REVIEW

**Comment by willstott101** [comment]
If `error` should use `unsafeLog(escapeHtml(...))` shouldn't `warning` do the same?

And in that train of thought, surely `exports.log(...)` is better than `exports.unsafeLog(escapeHtml(...))` ?

Then we can avoid the escape-html package in this file.

**Comment by alxhotel** [comment]
Agreed, @willstott101. We can use `exports.log(...)` since we are not using any HTML inside the error message.

**Comment by tsonge** [comment]
Thanks, you are right. We can just log the error/warning messages directly in the `textContent` property in the DOM elements without passing them through `escape-html`, since as alxhotel says, we are not using any HTML inside the error/warning messages that we're passing in, in the `client/index.js` file.

Fixed it.

**Comment by feross** [comment]
Thanks for the fix @tsonge! And thanks for the feedback on the PR everyone. Deployed to https://instant.io

**Pull request merged**
